name: Get Public IP

on:
  push:
    branches:
      - main

jobs:
  get-ip:
    runs-on: ubuntu-latest

    steps:
      - name: Get Public IP
        id: ip
        uses: haythem/public-ip@v1.3

      - name: Display Public IP
        run: echo "Current Public IP: ${{ steps.ip.outputs.ipv4 }}"
