name: Deploy to NCP VPC Server

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Get GitHub Actions IP
      id: ip
      uses: haythem/public-ip@v1.2

    - name: Configure NCP CLI
      run: |
        echo "${{ secrets.NCP_ACCESS_KEY }}" > ~/ncp-access-key
        echo "${{ secrets.NCP_SECRET_KEY }}" > ~/ncp-secret-key
        echo "NCP_ACCESS_KEY=$(cat ~/ncp-access-key)" >> $GITHUB_ENV
        echo "NCP_SECRET_KEY=$(cat ~/ncp-secret-key)" >> $GITHUB_ENV

    - name: Add GitHub Actions IP to NCP Security Group
      run: |
        ncp --access-key $NCP_ACCESS_KEY --secret-key $NCP_SECRET_KEY \
        vpc authorize-security-group-ingress-rule \
        --region ap-northeast-2 \
        --security-group-no ${{ secrets.SECURITY_GROUP_ID }} \
        --protocol TCP --port-range 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
    
    - name: Deploy via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          ./deploy.sh

    - name: Remove GitHub Actions IP from NCP Security Group
      run: |
        ncp --access-key $NCP_ACCESS_KEY --secret-key $NCP_SECRET_KEY \
        vpc revoke-security-group-ingress-rule \
        --region ap-northeast-2 \
        --security-group-no ${{ secrets.SECURITY_GROUP_ID }} \
        --protocol TCP --port-range 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
