name: Deploy to NCP VPC Server

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Get GitHub Actions IP
      id: ip
      uses: haythem/public-ip@v1.2

    - name: Install NCP CLI
      run: |
        sudo apt update && sudo apt install -y python3-pip
        pip3 install ncloud-cli

    - name: Add GitHub Actions IP to NCP Security Group
      run: |
        ncloud vpc authorize-security-group-ingress-rule \
          --access-key ${{ secrets.NCP_ACCESS_KEY }} \
          --secret-key ${{ secrets.NCP_SECRET_KEY }} \
          --region KR \
          --security-group-no ${{ secrets.SECURITY_GROUP_ID }} \
          --protocol TCP --port-range 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32

    - name: Deploy via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          ./deploy.sh

    - name: Remove GitHub Actions IP from NCP Security Group
      run: |
        ncloud vpc revoke-security-group-ingress-rule \
          --access-key ${{ secrets.NCP_ACCESS_KEY }} \
          --secret-key ${{ secrets.NCP_SECRET_KEY }} \
          --region KR \
          --security-group-no ${{ secrets.SECURITY_GROUP_ID }} \
          --protocol TCP --port-range 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
