name: Deploy to NCP VPC Server

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Get GitHub Actions IP
      id: ip
      uses: haythem/public-ip@v1.2

    - name: Install NCP CLI
      run: |
        wget https://www.ncloud.com/api/support/download/files/cli/CLI_1.1.23_20241121.zip
        unzip CLI_1.1.23_20241121.zip
        mv CLI_1.1.23_20241121/cli_linux ~/ncp-cli
        chmod +x ~/ncp-cli/ncloud
        echo "export PATH=$PATH:~/ncp-cli" >> ~/.bashrc
        source ~/.bashrc
        ~/ncp-cli/ncloud --version  # 설치 확인

    - name: Add GitHub Actions IP to NCP Security Group
      run: |
        ~/ncp-cli/ncloud vpc authorize-security-group-ingress-rule \
          --access-key ${{ secrets.NCP_ACCESS_KEY }} \
          --secret-key ${{ secrets.NCP_SECRET_KEY }} \
          --region KR \
          --security-group-no ${{ secrets.SECURITY_GROUP_ID }} \
          --protocol TCP --port-range 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32

    - name: Deploy via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          ./deploy.sh

    - name: Remove GitHub Actions IP from NCP Security Group
      run: |
        ~/ncp-cli/ncloud vpc revoke-security-group-ingress-rule \
          --access-key ${{ secrets.NCP_ACCESS_KEY }} \
          --secret-key ${{ secrets.NCP_SECRET_KEY }} \
          --region KR \
          --security-group-no ${{ secrets.SECURITY_GROUP_ID }} \
          --protocol TCP --port-range 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
